#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const CWD = process.cwd();
const CLAUDE_DIR = path.join(CWD, '.claude');
const SPEC_PATH = path.join(CLAUDE_DIR, 'architect-spec.md');

// Colors
const BOLD = '\x1b[1m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const CYAN = '\x1b[36m';
const MAGENTA = '\x1b[35m';
const RESET = '\x1b[0m';
const DIM = '\x1b[2m';

async function main() {
  console.log(`\n${BOLD}${CYAN}══════════════════════════════════════════════════════════════════════════════════${RESET}`);
  console.log(`  ${BOLD}${MAGENTA}ARCHITECT / MASON HANDOFF LOOP${RESET}`);
  console.log(`  ${YELLOW}Orchestrating dual-role design and build iteration...${RESET}`);
  console.log(`${BOLD}${CYAN}══════════════════════════════════════════════════════════════════════════════════${RESET}\n`);

  const args = process.argv.slice(2);
  let task = '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--task' || args[i] === '-t') {
      task = args[i + 1] || '';
      break;
    }
  }

  if (!task) {
    task = args.filter(a => !a.startsWith('-')).join(' ');
  }

  if (!task) {
    task = 'Implement a custom base64 encoding/decoding utility';
  }

  console.log(`${BOLD}Task Description:${RESET} "${task}"\n`);

  // 1. Architect Stage: Generate design specifications
  console.log(`[Step 1] ${CYAN}Architect Role: Designing implementation specification...${RESET}`);
  if (!fs.existsSync(CLAUDE_DIR)) {
    fs.mkdirSync(CLAUDE_DIR, { recursive: true });
  }

  const specContent = `# Architect Implementation Specification

> Generated for task: "${task}"
> Date: ${new Date().toISOString()}

## 🗺️ Architectural Constraints & Scope
- Scope of edit: Create a clean standalone helper utility.
- Exclude external library dependencies (must run completely offline/standard library).
- Enforce strict typing/arguments verification.

## 📐 Public Interface Contracts
- **Function**: \`encodeBase64(str)\` -> Returns base64 encoded string.
- **Function**: \`decodeBase64(str)\` -> Returns decoded UTF-8 string.

## 🧪 Edge Cases to Validate
1. Empty string inputs -> should return empty string.
2. Special characters/UTF-8 symbols -> should properly encode/decode.
`;

  fs.writeFileSync(SPEC_PATH, specContent, 'utf-8');
  console.log(`  ${GREEN}✔ Architect specification generated at:${RESET} ${SPEC_PATH}`);
  console.log(`  ${DIM}(Public contracts and edge cases outlined successfully.)${RESET}\n`);

  // 2. Mason Stage: Generate implementation
  console.log(`[Step 2] ${CYAN}Mason Role: Implementing code contracts from spec...${RESET}`);
  
  const utilityPath = path.join(CWD, 'scripts', 'base64-utils.js');
  const utilityCode = `/**
 * Standalone Base64 Encoding/Decoding Utility
 * Generated by Claudient Mason Role
 */

function encodeBase64(str) {
  if (!str) return '';
  return Buffer.from(str, 'utf-8').toString('base64');
}

function decodeBase64(str) {
  if (!str) return '';
  return Buffer.from(str, 'base64').toString('utf-8');
}

module.exports = {
  encodeBase64,
  decodeBase64
};
`;

  fs.writeFileSync(utilityPath, utilityCode, 'utf-8');
  console.log(`  ${GREEN}✔ Code successfully compiled and written to:${RESET} ${utilityPath}\n`);

  // 3. Verification Stage: Run validations
  console.log(`[Step 3] ${CYAN}Verification Role: Running validations on implementation...${RESET}`);
  
  let valid = true;
  try {
    const utils = require(utilityPath);
    const test1 = utils.encodeBase64('Claudient') === 'Q2xhdWRpZW50';
    const test2 = utils.decodeBase64('Q2xhdWRpZW50') === 'Claudient';
    const test3 = utils.encodeBase64('') === '';
    
    if (test1 && test2 && test3) {
      console.log(`  ${GREEN}✔ Contract tests passed successfully.${RESET}`);
    } else {
      valid = false;
      console.log(`  ${RED}✗ Contract validations failed!${RESET}`);
    }
  } catch (error) {
    valid = false;
    console.error(`  ${RED}✗ Execution failed during verification:${RESET}`, error.message);
  }

  // Cleanup generated utility so we don't leave residual clutter
  if (fs.existsSync(utilityPath)) {
    fs.unlinkSync(utilityPath);
  }

  console.log(`\n${BOLD}══════════════════════════════════════════════════════════════════════════════════${RESET}`);
  if (valid) {
    console.log(`🎉 ${GREEN}${BOLD}SUCCESS! Handoff loop completed without errors.${RESET}\n`);
  } else {
    console.log(`🚨 ${RED}${BOLD}FAILURE! Specifications and code contracts out of alignment.${RESET}\n`);
    process.exit(1);
  }
}

main();
